Initial Changes to To do Items
NShilu/DevOps-Course-Starter pull request #1
Opened 2021-11-30 00:44 UTC by NShilu

Please make sure you are raising this PR against your own repository and not the original. If it says https://github.com/CorndelWithSoftwire in the search bar right now, you are in the wrong place!

Please also don't forget to submit the PR's url to Aptem afterwards (by clicking on the corresponding exercise component, pasting the url in the textbox that appears and then pressing the finish button).

2021-12-06 18:11 UTC, JackMead requested changes
Nice work, I was easily able to run the app and see the to-dos so the first part is done, but it doesn't look like you've completed the second part which is to also add functionality for creating new to-dos; maybe something you forgot to push? Feel free to reach out if you're having issues 🙂

2021-12-07 09:15 UTC, NShilu commented
Hi Jack and Alex,

I believe I followed the instructions and created the Pull request for a new branch ‘exercise-1’, I am unsure what and where I missed ?

Shall I arrange a quick session with one of you to address this please

Thanks
Nirav


Nirav Shilu
Professional Services Consultant

retaininternational part of the Capita Group

***@***.***
Office +44 (0) 20 7538 4774
Support +44 (0) 20 7538 9237
Email: ***@***.******@***.***>
Web: www.retaininternational.com<http://www.retaininternational.com/>

From: JackMead ***@***.***>
Sent: 06 December 2021 18:11
To: NShilu/DevOps-Course-Starter ***@***.***>
Cc: Shilu, Nirav (Capita Retain) ***@***.***>; Author ***@***.***>
Subject: Re: [NShilu/DevOps-Course-Starter] Initial Changes to To do Items (PR #1)


**EXTERNAL**

@JackMead requested changes on this pull request.

Nice work, I was easily able to run the app and see the to-dos so the first part is done, but it doesn't look like you've completed the second part which is to also add functionality for creating new to-dos; maybe something you forgot to push? Feel free to reach out if you're having issues 🙂

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/NShilu/DevOps-Course-Starter/pull/1#pullrequestreview-824294120>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AWOC3HWG63QXFHH25F6AEWLUPT4ERANCNFSM5JAO4YEQ>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.


This message has been scanned by Capita’s systems, but if you believe it to be spam then click here<https://www.mailcontrol.com/sr/MZbqvYs5QwJvpeaetUwhCQ==> to report this email as spam.

This email originates from outside of Capita.
Keep this in mind before responding, opening attachments or clicking any links. Unless you recognise the sender and know the content is safe.
If in any doubt, the grammar and spelling are poor, or the name doesn't match the email address then please contact the sender via an alternate known method.



This email is security checked and subject to the disclaimer on web-page: https://www.capita.com/email-disclaimer.aspx

2021-12-09 16:14 UTC, Jonesey13 approved these changes
Looks good to me. Left a few comments but feel free to merge in when ready 👍

2021-12-09 16:14 UTC, Jonesey13 commented on todo_app/app.py
> +    return redirect('/')
To keep consistent spacing
```suggestion
    title=request.form.get('title')
    add_item(title)
    return redirect('/')
```

2021-12-09 16:14 UTC, Jonesey13 commented on todo_app/app.py
> +def index_addItem():
Convention in Python is for method names to be `lower_snake_case` (see PEP8: https://www.python.org/dev/peps/pep-0008/)
```suggestion
def add_item():
```

2021-12-09 16:14 UTC, Jonesey13 commented on todo_app/app.py
> +
```suggestion
@app.route('/addItem', methods=['POST'])
```

2021-12-09 16:17 UTC, merged